all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: /path/to/your/ansible_ed25519

  children:

    # All nodes monitored by Prometheus
    monitored_nodes:
      children:
        vm_nodes:
        proxmox_nodes:
      hosts:
        prox-monitoring:

    # Virtual machines managed by Ansible
    vm_nodes:
      hosts:
        prox-management:
          ansible_host: 192.168.1.10
          ansible_user: your_system_user
          ansible_ssh_private_key_file: /path/to/your/proxmox_vms_ed25519

        prox-testing:
          ansible_host: 192.168.1.20

    # Proxmox cluster nodes
    proxmox_nodes:
      hosts:
        pve01:
          ansible_host: 192.168.1.30

        pve02:
          ansible_host: 192.168.1.31
