all:
  vars:
    ansible_user: ansible
    system_user: kacper

  children:
    monitoring:
      hosts:
        prox-monitoring:
          ansible_host: 10.10.10.40

local:
  hosts:
    localhost:
      ansible_connection: local
