all:
  vars:
    ansible_user: ansible

  children:
    nodes:
      hosts:
        
local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: true
      ansible_become_user: root
      ansible_host: 10.10.10.244
