- name: Generate SSH key for ansible automation user
  hosts: localhost

  tasks:
    - name: Ensure that .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ bootstrap_system_user }}/.ssh/.bootstrap"
        state: directory
        owner: "{{ bootstrap_system_user }}"
        group: "{{ bootstrap_system_user }}"
        mode: '0700'

    - name: Generate SSH key for ansible user
      ansible.builtin.openssh_keypair:
        path: "/home/{{ bootstrap_system_user }}/.ssh/.bootstrap/ansible_ed25519"
        type: ed25519
        owner: "{{ bootstrap_system_user }}"
        group: "{{ bootstrap_system_user }}"
        mode: '0600'
        state: present
