- name: Create directory /opt/prometheus if it doesn't exist
  ansible.builtin.file:
    name: /opt/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Prometheus targets directory
  ansible.builtin.file:
    path: /opt/prometheus/targets
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: ['prometheus']
    